loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  useTestSchema: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 2
  image:
    tag: 3.5.3
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
minio:
  enabled: true

gateway:
  enabled: false
chunksCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0