serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector.monitoring.svc:9090']
server:
  image:
    repository: quay.io/prometheus/prometheus
    tag: "v3.1.0"