apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Tempo
    type: tempo
    access: proxy
    editable: true
    uid: tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        filterByTraceID: true
        spanStartTimeShift: -5s
        spanEndTimeShift: 5s
  - name: Loki
    type: loki
    access: proxy
    editable: true
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          name: "TraceID"
          url: "$${__value.raw}"