receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kong-gateway'
        scrape_interval: 5s
        static_configs:
        - targets: ['kong:8100']
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:8888']
processors:
  batch:
  resource/kong-gateway:
    attributes:
      - action: upsert
        key: service.name
        value: kong-gateway
      - action: upsert
        key: component.name
        value: kong-http-log
exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
    encoding: json
service:
  telemetry:
    metrics:
      address: ":8888"
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource/kong-gateway
      exporters:
        - otlphttp
    metrics:
      receivers:
        - prometheus
      processors: []
      exporters:
        - prometheus
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - otlp/tempo