apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-http-log
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  http_endpoint: http://fluent-bit.monitoring.svc:8080
  custom_fields_by_lua:
    traceid: |
      local h = kong.request.get_header('traceparent')
      return h:match("%-([a-f0-9]+)%-[a-f0-9]+%-")
    spanid: |
      local h = kong.request.get_header('traceparent')
      return h:match("%-[a-f0-9]+%-([a-f0-9]+)%-")
plugin: http-log