tenant:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-02-03T21-03-04Z
  configSecret:
    accessKey: tempo
    secretKey: supersecret
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 2Gi
  metrics:
    enabled: true
  buckets:
    - name: tempo-traces