gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.9"
  env:
    router_flavor: "expressions"
    tracing_instrumentations: "all"
    tracing_sampling_rate: "1.0"
  manager:
    enabled: false
controller:
  ingressController:
    env:
      dump_config: "true"
      dump_sensitive_config: "true"
      log_level: info