env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_AUTH_DISABLE_LOGIN_FORM: true
  GF_USERS_DEFAULT_THEME: light
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    kong:
      gnetId: 7424
      revision: 11
      # url: https://grafana.com./api/dashboards/7424/revisions/11/download
      datasource: Prometheus
    otel-collector:
      gnetId: 15983
      revision: 23
      # url: https://grafana.com./api/dashboards/15983/revisions/23/download
      datasource: Prometheus
    kong-ingress-controller:
      json: |
        {"__inputs":[],"__elements":[],"__requires":[{"type":"grafana","id":"grafana","name":"Grafana","version":"8.3.4"},{"type":"panel","id":"histogram","name":"Histogram","version":""},{"type":"panel","id":"stat","name":"Stat","version":""}],"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","target":{"limit":100,"matchAny":false,"tags":[],"type":"dashboard"},"type":"dashboard"}]},"editable":true,"fiscalYearStartMonth":0,"graphTooltip":0,"id":null,"links":[],"liveNow":false,"panels":[{"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"custom":{"fillOpacity":80,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineWidth":1},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":5000}]},"unit":"ms"},"overrides":[{"matcher":{"id":"byName","options":"ingress_controller_configuration_push_duration_milliseconds_bucket{container=\"ingress-controller\",endpoint=\"cmetrics\",instance=\"10.244.0.13:10255\",job=\"trk-kong-proxy\",le=\"+Inf\",namespace=\"default\",pod=\"trk-kong-688c5dbdf7-p7vjc\",protocol=\"db-less\",service=\"trk-kong-proxy\",success=\"true\"}"},"properties":[{"id":"color","value":{"fixedColor":"green","mode":"fixed"}}]}]},"gridPos":{"h":16,"w":12,"x":0,"y":0},"id":2,"options":{"bucketOffset":0,"legend":{"calcs":[],"displayMode":"list","placement":"bottom"}},"targets":[{"exemplar":true,"expr":"ingress_controller_configuration_push_duration_milliseconds_bucket","interval":"","legendFormat":"","refId":"A"}],"title":"Configuration push duration (ms)","type":"histogram"},{"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"mappings":[],"noValue":"0","thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":4,"w":12,"x":12,"y":0},"id":4,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"text":{},"textMode":"auto"},"pluginVersion":"8.3.4","targets":[{"exemplar":true,"expr":"ingress_controller_configuration_push_count_total{success=\"true\"}","format":"time_series","interval":"","legendFormat":"","refId":"A"}],"title":"Successful configuration pushes","type":"stat"},{"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"mappings":[],"min":-7,"noValue":"0","thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"#EAB839","value":1},{"color":"red","value":10}]}},"overrides":[]},"gridPos":{"h":4,"w":12,"x":12,"y":4},"id":11,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"text":{},"textMode":"auto"},"pluginVersion":"8.3.4","targets":[{"exemplar":true,"expr":"sum by (failure_reason) (ingress_controller_configuration_push_count_total{success=\"false\"})","instant":false,"interval":"","legendFormat":"","refId":"A"}],"title":"Failed configuration pushes","type":"stat"},{"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"mappings":[],"noValue":"0","thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":4,"w":12,"x":12,"y":8},"id":10,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"text":{},"textMode":"auto"},"pluginVersion":"8.3.4","targets":[{"exemplar":true,"expr":"ingress_controller_translation_count_total{success=\"true\"}","interval":"","legendFormat":"","refId":"A"}],"title":"Successful configuration translations","type":"stat"},{"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"mappings":[],"noValue":"0","thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":20}]}},"overrides":[]},"gridPos":{"h":4,"w":12,"x":12,"y":12},"id":12,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"text":{},"textMode":"auto"},"pluginVersion":"8.3.4","targets":[{"exemplar":true,"expr":"ingress_controller_translation_count_total{success=\"false\"}","interval":"","legendFormat":"","refId":"A"}],"title":"Failed configuration translations","type":"stat"}],"refresh":"5s","schemaVersion":34,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-15m","to":"now"},"timepicker":{},"timezone":"","title":"Kong ingress controller","uid":"SaGwMOtnz","version":2,"gnetId":15662}
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc:3100
      access: proxy
      isDefault: false
      jsonData:
        derivedFields:
          - datasourceUid: Jaeger
            matcherType: label
            matcherRegex: trace_id
            name: "TraceID"
            url: "$${__value.raw}"
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc
      access: proxy
      isDefault: true
    - name: Jaeger
      type: jaeger
      url: http://jaeger-query.monitoring.svc:16686
      access: proxy
      isDefault: false
      jsonData:
        tracesToLogs:
          datasourceUid: Loki